<?php

$adminAllowedEmails = env('DIGESTPIPE_ADMIN_ALLOWED_EMAILS', '');

if (! is_string($adminAllowedEmails)) {
    $adminAllowedEmails = '';
}

return [
    'ai' => [
        'driver' => env('DIGESTPIPE_AI_DRIVER', 'fake'),
    ],

    'admin' => [
        'allowed_emails' => array_values(array_filter(array_map(
            static fn (string $email): string => trim($email),
            explode(',', $adminAllowedEmails),
        ), static fn (string $email): bool => $email !== '')),
    ],

    'analysis' => [
        'model' => env('DIGESTPIPE_ANALYSIS_MODEL', env('OPENAI_MODEL', 'gpt-4o-mini')),
        'batch_limit' => (int) env('DIGESTPIPE_ANALYSIS_BATCH_LIMIT', 10),
        'daily_limit' => (int) env('DIGESTPIPE_ANALYSIS_DAILY_LIMIT', 100),
        'max_input_chars' => (int) env('DIGESTPIPE_ANALYSIS_MAX_INPUT_CHARS', 8000),
        'schema_version' => env('DIGESTPIPE_ANALYSIS_OUTPUT_SCHEMA_VERSION', '1.0'),
    ],

    'openai' => [
        'api_key' => env('OPENAI_API_KEY'),
        'model' => env('OPENAI_MODEL', 'gpt-4o-mini'),
        'request_timeout' => (int) env('OPENAI_REQUEST_TIMEOUT', 60),
        'max_retries' => (int) env('OPENAI_MAX_RETRIES', 2),
    ],

    'content' => [
        'fetch_timeout' => (int) env('DIGESTPIPE_CONTENT_FETCH_TIMEOUT', 15),
        'max_bytes' => (int) env('DIGESTPIPE_CONTENT_MAX_BYTES', 1048576),
        'max_chars' => (int) env('DIGESTPIPE_CONTENT_MAX_CHARS', 8000),
        'min_chars' => (int) env('DIGESTPIPE_CONTENT_MIN_CHARS', 200),
        'user_agent' => env('DIGESTPIPE_CONTENT_USER_AGENT', 'digestpipe/0.1 (+structured digest pipeline)'),
    ],

    'feed_sources' => [
        [
            'key' => 'hacker_news',
            'name' => 'Hacker News',
            'url' => 'https://news.ycombinator.com/rss',
            'language' => 'en',
            'enabled' => true,
            'analysis_enabled' => true,
            'tier' => 'core',
            'category' => 'aggregator',
        ],
        [
            'key' => 'lobsters_programming',
            'name' => 'Lobsters / Programming',
            'url' => 'https://lobste.rs/t/programming.rss',
            'language' => 'en',
            'enabled' => true,
            'analysis_enabled' => true,
            'tier' => 'core',
            'category' => 'programming',
        ],
        [
            'key' => 'lobsters_web',
            'name' => 'Lobsters / Web',
            'url' => 'https://lobste.rs/t/web.rss',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'web',
        ],
        [
            'key' => 'lobsters_linux',
            'name' => 'Lobsters / Linux',
            'url' => 'https://lobste.rs/t/linux.rss',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'linux',
        ],
        [
            'key' => 'lobsters_devops',
            'name' => 'Lobsters / DevOps',
            'url' => 'https://lobste.rs/t/devops.rss',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'devops',
        ],
        [
            'key' => 'php_weekly',
            'name' => 'PHP Weekly',
            'url' => 'https://www.phpweekly.com/feed',
            'language' => 'en',
            'enabled' => true,
            'analysis_enabled' => true,
            'tier' => 'core',
            'category' => 'php',
        ],
        [
            'key' => 'laravel_news',
            'name' => 'Laravel News',
            'url' => 'https://laravel-news.com/feed',
            'language' => 'en',
            'enabled' => true,
            'analysis_enabled' => true,
            'tier' => 'core',
            'category' => 'laravel',
        ],
        [
            'key' => 'stitcher_io',
            'name' => 'Stitcher.io',
            'url' => 'https://stitcher.io/feed',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'php',
        ],
        [
            'key' => 'php_internals_news',
            'name' => 'PHP Internals News',
            'url' => 'https://phpinternals.news/feed.rss',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'php',
        ],
        [
            'key' => 'php_watch',
            'name' => 'PHP.Watch',
            'url' => 'https://php.watch/feed',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'php',
        ],
        [
            'key' => 'aws_news',
            'name' => 'AWS News',
            'url' => 'https://aws.amazon.com/new/feed/',
            'language' => 'en',
            'enabled' => true,
            'analysis_enabled' => true,
            'tier' => 'core',
            'category' => 'aws',
        ],
        [
            'key' => 'zenn_php',
            'name' => 'Zenn / PHP',
            'url' => 'https://zenn.dev/topics/php/feed',
            'language' => 'ja',
            'enabled' => true,
            'analysis_enabled' => true,
            'tier' => 'core',
            'category' => 'php',
        ],
        [
            'key' => 'zenn_laravel',
            'name' => 'Zenn / Laravel',
            'url' => 'https://zenn.dev/topics/laravel/feed',
            'language' => 'ja',
            'enabled' => true,
            'analysis_enabled' => true,
            'tier' => 'core',
            'category' => 'laravel',
        ],
        [
            'key' => 'qiita_php',
            'name' => 'Qiita / PHP',
            'url' => 'https://qiita.com/tags/php/feed.atom',
            'language' => 'ja',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'php',
        ],
        [
            'key' => 'qiita_laravel',
            'name' => 'Qiita / Laravel',
            'url' => 'https://qiita.com/tags/laravel/feed.atom',
            'language' => 'ja',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'laravel',
        ],
        [
            'key' => 'hackaday',
            'name' => 'Hackaday',
            'url' => 'https://hackaday.com/blog/feed/',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'hardware',
        ],
        [
            'key' => 'selfh_st',
            'name' => 'selfh.st',
            'url' => 'https://selfh.st/rss/',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'self-hosted',
        ],
        [
            'key' => 'noted_lol',
            'name' => 'Noted.lol',
            'url' => 'https://noted.lol/rss',
            'language' => 'en',
            'enabled' => false,
            'analysis_enabled' => false,
            'tier' => 'candidate',
            'category' => 'self-hosted',
        ],
    ],

    'selection' => [
        'enabled' => true,
        'default_score' => 0,
        'analysis_threshold' => 1,
        'skip_threshold' => -50,

        'positive_keywords' => [
            // PHP / Laravel
            'PHP' => 12,
            'Laravel' => 15,
            'Composer' => 10,
            'Symfony' => 8,
            'PHPStan' => 8,
            'PHP-CS-Fixer' => 8,
            'Pest' => 6,
            'PHPUnit' => 6,

            // AWS / Cloud
            'AWS' => 12,
            'Amazon Web Services' => 12,
            'EC2' => 10,
            'ECS' => 12,
            'Fargate' => 10,
            'Lambda' => 10,
            'RDS' => 10,
            'Aurora' => 10,
            'CloudFront' => 10,
            'S3' => 8,
            'IAM' => 8,
            'Route 53' => 8,
            'クラウド' => 8,

            // Linux / Server / Infra
            'Linux' => 10,
            'Bash' => 8,
            'Shell' => 6,
            'CLI' => 8,
            'systemd' => 8,
            'nginx' => 8,
            'Apache' => 6,
            'Ubuntu' => 6,
            'Debian' => 6,
            'Alpine Linux' => 6,
            'シェル' => 6,
            'コマンドライン' => 8,

            // Database
            'MySQL' => 12,
            'PostgreSQL' => 10,
            'Postgres' => 10,
            'SQLite' => 8,
            'MariaDB' => 6,
            'Redis' => 6,
            'Valkey' => 6,
            'ポスグレ' => 8,
            'データベース' => 6,

            // Containers / Dev Environment
            'Docker' => 12,
            'Docker Compose' => 12,
            'Compose' => 6,
            'container' => 6,
            'containers' => 6,
            'コンテナ' => 8,

            // Self-hosted / Homelab
            'homelab' => 12,
            'home lab' => 10,
            'self-hosted' => 12,
            'self hosted' => 12,
            'selfhosting' => 10,
            'NAS' => 8,
            'Proxmox' => 8,
            'TrueNAS' => 8,
            'ホームラボ' => 10,
            'セルフホスト' => 12,
            '自宅サーバー' => 12,
            '自宅サーバ' => 12,

            // Hardware / IoT
            'IoT' => 8,
            'Raspberry Pi' => 10,
            'RasPi' => 8,
            'ESP32' => 10,
            'Arduino' => 6,
            'microcontroller' => 6,
            'embedded' => 6,
            'ラズパイ' => 10,
            'ラズベリーパイ' => 10,
            'マイコン' => 8,
            '組み込み' => 6,

            // Web / API
            'WebAssembly' => 8,
            'WASM' => 8,
            'Web API' => 8,
            'REST API' => 8,
            'HTTP API' => 8,
            'OpenAPI' => 6,
            'browser' => 4,
            'browsers' => 4,
            'ブラウザ' => 4,
            'API' => 3,
        ],

        'negative_keywords' => [
            // Crypto / Web3: strong negative
            'crypto' => -100,
            'cryptocurrency' => -100,
            'bitcoin' => -100,
            'ethereum' => -100,
            'blockchain' => -100,
            'web3' => -100,
            'NFT' => -100,
            'DAO' => -80,
            'DeFi' => -80,
            'tokenomics' => -80,
            'ビットコイン' => -100,
            '仮想通貨' => -100,
            '暗号資産' => -100,
            '暗号通貨' => -100,
            'イーサリアム' => -100,
            'ブロックチェーン' => -100,
            'トークノミクス' => -80,

            // Ambiguous crypto/business terms: weak to medium negative
            // Do not make "token" too strong because API token / CSRF token / access token are valid technical topics.
            'token' => -10,
            'tokens' => -10,
            'トークン' => -10,

            // Startup / investment / business growth
            'VC' => -20,
            'venture capital' => -30,
            'startup funding' => -40,
            'seed round' => -40,
            'angel investor' => -30,
            'fundraising' => -30,
            'funding round' => -40,
            'Series A' => -30,
            'Series B' => -30,
            'monetization' => -20,
            'growth hacking' => -30,
            'スタートアップ' => -20,
            'ベンチャー' => -20,
            'ベンチャーキャピタル' => -30,
            '資金調達' => -40,
            'シードラウンド' => -40,
            'エンジェル投資' => -30,
            '投資家' => -20,
            'マネタイズ' => -20,
            'グロースハック' => -30,
            'グロースハッキング' => -30,
        ],
    ],
];
